givenStatement = "Durango, CO, offers an eclectic mix of dinner options that cater to a wide range of tastes, from casual to fine dining. The dining scene reflects the town’s unique blend of Western heritage and adventurous spirit, making it a culinary destination for both locals and visitors. For those seeking a refined experience, Durango has several upscale dining spots where locally sourced ingredients and creative dishes take center stage. Menus often feature steaks, game meats, and fresh fish, all prepared with an emphasis on quality and presentation. Many of these establishments offer farm-to-table experiences, focusing on sustainability and the freshest seasonal ingredients. Paired with expertly curated wine lists and craft cocktails, these restaurants provide a complete dining experience, perfect for a romantic evening or a special occasion. If you’re looking for a more relaxed setting, Durango’s casual dining scene offers plenty of variety. From hearty comfort food to globally inspired cuisine, there’s something for every palate. Burgers, pizza, and barbeque are popular options, with many eateries putting a local spin on classic dishes by incorporating regional ingredients such as green chili or bison. For those who enjoy international flavors, there are plenty of options, from Mexican and Italian to Thai and Indian cuisine, ensuring that you can embark on a culinary journey without leaving town. Vegetarian and vegan diners will also find plenty to choose from, as Durango’s restaurant scene caters well to those seeking plant-based options. Many menus feature creative vegetarian dishes or offer vegan alternatives, showcasing the town’s commitment to inclusivity in its food culture. Salads, grain bowls, and vegetable-forward dishes are made with the same attention to flavor and presentation as their meat-based counterparts. A major highlight of dining in Durango is the strong emphasis on local craft beer. Many dinner spots in town offer extensive beer lists featuring brews from local breweries, making it easy to pair your meal with a perfect pint. Whether you're into IPAs, stouts, or lighter ales, there's a brew for everyone. Durango’s dinner scene is also known for its inviting atmospheres. Many restaurants have cozy, rustic interiors, with outdoor seating options that allow diners to enjoy the crisp Colorado air and scenic views. Whether it’s a casual night out or a more formal dinner, Durango’s restaurants deliver quality food with a touch of local charm."

def wordCount(givenStatement):
    index = 0
    countArray = givenStatement.split(' ')
    for count in countArray:
        index += 1

    print(index)
wordCount(givenStatement)